### ISSUE TITLE
Errors when trying to work with files that were modified by TexTools

### ISSUE THREAD

**Issue by endervad** [divergentdave/tomestone-utils#2]
Hello,

First of all, thank you for creating this program. I'm a head translator of FFXIV to Russian language, and right now we're struggling without a program that can reliably extract **all** of the game text files. FFXIV Explorer is very outdated and doesn't show a lot of the newer files which makes it quite troublesome to hunt down and then extract individual files via TexTools. Seems like your program by design should be more than enough for our needs since it's possible to use it in scripts, which I greatly appreciate.

I've managed to compile your program. It seems like README is not up to date since I also needed to do the following steps:
* Run `cargo build --release` from `tomestone-dump` subfolder. Otherwise if run from the root folder it compiles everything and requires `qmake` along the way
* There needs to be `sqlite3.lib` in root folder for compiling and then `sqlite3.dll` together with the output executable
* This is probably out of scope of your program but some clarification on installing MSVC++ Build Tools for Rust and overall minimum software requirements would be awesome

After I was able to make the program work (`.\tomestone-dump.exe help` shows help message) I keep getting the following message with any subcommand:
```
error: couldn't open path hash database, The system cannot find the path specified. (os error 3)
```
I've tried specifying the path via both ENV variable and `--ffxiv-install-dir` command-line option. The path itself is up until `FINAL FANTASY XIV Online` folder, just like in `.env.example`. I also tried doing the same from elevated prompt. I have Steam version that is located on a different disk. The folder-file structure should be the same though - it's still `FINAL FANTASY XIV Online\game\sqpack` and so on. I also tried to clean up SqPacks files via "Start Over" in TexTools. I'm not sure if it's required though.

How can I see what path Rust actually sees? I don't know Rust at all unfortunately.

**Comment by endervad** [comment]
Thanks a lot for such fast response!

The program compiles now from clean repo without needing to do anything else which is awesome :)

I also tried before to compile from Linux/WSL2 but wasn't able to figure out what do with toolchains and how to get the right one. Though it seems like there's no need since it's compiling perfectly fine on Windows as long as MSVC is installed correctly. And SQLite library is indeed bundled now, so there's no need for separate DLL anymore.

When trying to use the program, I have other errors now:
* `.\tomestone-dump.exe discover_paths` (using ENV variable) - I get this:
```
error: file not found
```
* `.\tomestone-dump.exe --ffxiv-install-dir "E:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online" discover_paths` - I get this:
```
error: error: Verify
```
The database at %APPDATA%\David Cook\Tomestone\data\paths.db is created, but in both cases it seems like it's empty. Between testings I backed up the database into a separate file and tried again. Comparing the results I've found out that the databases are identical. And looking at their bytes, I think they have only the structure but no data itself. I've attached the database in ZIP archive.
[paths.zip](https://github.com/divergentdave/tomestone-utils/files/8204503/paths.zip)

**Comment by divergentdave** [comment]
The first is likely an error with not being able to find one of the files inside the packs, either root.exl, an .exh file, or an .exd file. Do you run `cargo run --release --bin tomestone-dump -- raw exd/root.exl`? Or `cargo run --release --bin tomestone-dump -- exd FCAuthority`?

The second issue is from one of three places in the parser, here it should be either an unexpected version number in a header or a bad SHA-1 checksum in one of the two headers at the start of the file. What's the provenance of the files you're running this on? Are they original files or edited, and which region? Thus far I have only tested with the English language, Windows, non-Steam distribution, and the Endwalker benchmark.

**Comment by endervad** [comment]
```
PS> .\tomestone-dump.exe raw exd/root.exl
error: file not found
PS> .\tomestone-dump.exe exd FCAuthority
error: loading dataset failed: file not found
```
By the way, does it matter whether I run *.exe like above or should I use `cargo run` etc?

The game files should be original. At least I think they become original after doing "Start Over" in TexTools. At least FFXIV Explorer is able to read files even in modded state. The game's language is currently set to English but it shouldn't matter since the game has English, German, French, and Japanese languages in it.

Also I've tried the program with EW benchmark and I can confirm that it indeed works with benchmark.

**Comment by endervad** [comment]
I've installed FFXIV on a separate VM from scratch, and the program now works with it. So it seems like it can't currently accept files that were modded by TexTools. Is this support planned? And if so, which files can I send that would help you in this?

**Comment by divergentdave** [comment]
No, invoking the executable directly should work just fine. `cargo run` will build an executable if it is out of date, and then run it, plus it's a little more ergonomic for switching between debug and release builds, but otherwise you're not losing anything.

To address this, I can remove the parser error when these checksums don't match, and emit a warning instead.

**Comment by endervad** [comment]
I tried my best at debugging the issue and now I feel incredibly dumb - I've put the path to the game with double quotes. Once I removed them, everything worked perfectly fine. I'm very sorry for bothering with this one, and I'm gonna close it.

**Comment by divergentdave** [comment]
Ah phew, glad you got it sorted. No worries.
